apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: laboratory
  name: laboratory
  namespace: laboratory
spec:
  replicas: 3
  selector:
    matchLabels:
      app: laboratory
  template:
    metadata:
      labels:
        app: laboratory
    spec:
      containers:
      - name: laboratory
        image: gazizovemil/laboratory:latest
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: laboratory
  name: laboratory-svc
  namespace: laboratory
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: laboratory
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: laboratory-ingress
  namespace: laboratory
spec:
  rules:
  - host:
    http:
      paths:
      - backend:
          service:
            name: laboratory-svc
            port:
              number: 5000
        path: /up
        pathType: ImplementationSpecific
